# Generated by Django 4.2.2 on 2023-06-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_rename_settings_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
    ]
