# Generated by Django 4.2.2 on 2023-07-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_setting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Иконка'),
        ),
    ]
