# Generated by Django 4.2.2 on 2023-07-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
