# Generated by Django 4.2.2 on 2023-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=365, verbose_name='Регион')),
                ('city', models.CharField(max_length=365, verbose_name='Город')),
            ],
        ),
    ]
