# Generated by Django 4.2.2 on 2023-07-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
